### PR TITLE
Added insert multiple rows support

### PR DESCRIPTION
**Pull request by Sanchiz1**
1. **Updated `inserts` Field**:  
   - Changed the `value` property to `values: Vec<Box<dyn ToSql>>`.  

2. **Refactored `insert` Method**:  
   - Updated the `insert` method to store values in new property. 

3. **Added `insert_many` Method**:  
   - Introduced the `insert_many` method to handle bulk insertion of multiple rows.

### CODE REVIEW

**Comment by tjardoo** [comment]
Thanks for the PR! Looks good to me.

This setup works if all the fields are of the same type - in the example all the fields are of the type `&str`. If I add a vector with only a field 'age' for example of the type `u32` it also works. But when we have field with different type like - name, email of `&str` and age of `u32` it doesn't work. Do you have any suggestion on how we could cover this?

```rust
let rows = vec![
    vec![
        ("name", "Alice"),
        ("email", "alice@example.com"),
        ("age", 21),
    ],
    vec![("name", "Bob"), ("email", "bob@example.com"), ("age", 22)],
];

let query = Eloquent::query().table("users").insert_many(rows);

assert_eq!(
    query.sql().unwrap(),
    "INSERT INTO users (name, email, age) VALUES ('Alice', 'alice@example.com' 21), ('Bob', 'bob@example.com', 22)"
);
```

**Comment by Sanchiz1** [comment]
Hi, thank you for reviewing the PR and for raising this excellent point! To handle fields of mixed types we can update the implementation to use Box<dyn ToSql> for the value type. The throw back will be the need to construct rows as using Box::new()

``` rust
let rows = vec![
        vec![
            ("name", Box::new("Alice") as Box<dyn ToSql>),
            ("email", Box::new("alice@example.com") as Box<dyn ToSql>),
            ("age", Box::new(21) as Box<dyn ToSql>),
        ],
        vec![
            ("name", Box::new("Bob") as Box<dyn ToSql>),
            ("email", Box::new("bob@example.com") as Box<dyn ToSql>),
            ("age", Box::new(22) as Box<dyn ToSql>),
        ],
    ];
``` 

But we can introduce some kind of rows builder for simpler code.

**Comment by tjardoo** [comment]
Thanks for adjustments. That works but I don't really like the wrapping in a Box and typing it every time with `as Box<dyn ToSql>`.

What do you think of this? Feel free to adjust.

```rust
let rows = vec![
    eloquent_sql_row! {
        "name" => "Alice",
        "email" => "alice@example.com",
        "age" => 21,
        "is_active" => true,
    },
    eloquent_sql_row! {
        "name" => "Bob",
        "email" => "bob@example.com",
        "age" => 22,
        "is_active" => false,
    },
];

let query = Eloquent::query().table("users").insert_many(rows);

assert_eq!(
    query.sql().unwrap(),
    "INSERT INTO users (name, email, age, is_active) VALUES ('Alice', 'alice@example.com', 21, true), ('Bob', 'bob@example.com', 22, false)"
);
```

and then in the `eloquent_core\src\lib.rs` we add this macro.

```rust
#[macro_export]
macro_rules! eloquent_sql_row {
    ($($key:expr => $value:expr),* $(,)?) => {
        vec![
            $(($key, Box::new($value) as Box<dyn ToSql>)),*
        ]
    };
}
```

```rust
pub fn insert_many(mut self, rows: Vec<Vec<(&str, Box<dyn ToSql>)>>) -> Self {
    rows.into_iter().for_each(|row| self.add_row(row));

    self
}

fn add_insert(&mut self, column: &str, value: Box<dyn ToSql>) {
    if let Some(insert) = self.inserts.iter_mut().find(|i| i.column == column) {
        insert.values.push(value);
    } else {
        self.inserts.push(Insert {
            column: column.to_string(),
            values: vec![value],
        });
    }
}

fn add_row(&mut self, row: Vec<(&str, Box<dyn ToSql>)>) {
    row.into_iter()
        .for_each(|(column, value)| self.add_insert(column, value));
}
```

I also did try this using a HashMap that does work but as the hash is different each time the order of the columns to be inserted is too - and that prevented me to get the assertion to work every time.

**Comment by Sanchiz1** [comment]
Great suggestion! 
1. Created macro:
``` rust
#[macro_export]
macro_rules! eloquent_sql_row {
    ($($key:expr => $value:expr),* $(,)?) => {
        vec![
            $(($key, Box::new($value) as Box<dyn $crate::ToSql>)),*
        ]
    };
}
```

2. Updated insert_many method documentation.

**Comment by Sanchiz1** [comment]
Created validator that checks for equal number of values per column across inserts, prevents creating query with rows with different values.

**Comment by tjardoo** [comment]
Thanks a lot. Nice addition! Will merge it.

**Pull request merged**
